export interface Client {
  id: string
  name: string
  phone: string
  altPhone: string
  email: string
  status: string
  city: string
  occupation: string
  aadharNumber: string
  panNumber?: string
  assignedTo: string
  alloc_adv?: string
  alloc_adv_at?: any
  alloc_adv_secondary?: string
  alloc_adv_secondary_at?: any
  convertedAt?: any
  convertedFromLead?: boolean
  creditCardDues?: string
  lastModified?: any
  lastUpdated?: any
  leadId: string
  monthlyFees?: string
  monthlyIncome?: string
  personalLoanDues?: string
  remarks?: string
  salesNotes?: string
  source_database?: string
  startDate: string
  tenure?: string
  banks?: Array<{
    id: string;
    accountNumber: string;
    bankName: string;
    loanAmount: string;
    loanType: string;
  }>
  documents?: Array<{
    name: string;
    type: string;
    bankName: string;
    accountType: string;
    url: string;
    htmlUrl: string;
    createdAt: string;
  }>
  adv_status?: string
  documentUrl?: string
  documentName?: string
  documentUploadedAt?: any
  dob?: string
  message: string
  sentAgreement?: boolean
  request_letter?: boolean
  latestRemark?: {
    remark: string;
    advocateName: string;
    timestamp: any;
  }
} 