name: Backup Firestore

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  PROJECT_ID: amacrm-76fd1
  BUCKET: gs://backup-amacrm
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.BACKUP_KEY_GCP }}
    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
    - run: gcloud info
    - run: gcloud config set project $PROJECT_ID
    - run: gcloud firestore export $BUCKET