name: Backup Firestore

on:
  schedule:
    - cron: '0 0 * * 0'

env:
  PROJECT_ID: amacrm-76fd1
  BUCKET: gs://backup-amacrm
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.BACKUP_KEY_GCP }}
        export_default_credentials: true
    - run: gcloud info
    - run: gcloud config set project $PROJECT_ID
    - run: gcloud firestore export $BUCKET